apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: web
          image: quay.io/hfisli/flask-demo
          ports:
            - containerPort: 8080
          env:
            - name: FLASK_APP
              value: "app.py"
            - name: FLASK_ENV
              value: "dev"
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: "myapp"
